language: ruby
rvm:
  - 2.1.0

env:
  - DB=postgresql

bundler_args: --without development

cache: bundler

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake test:units
  - xvfb-run bundle exec rake test:integration

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database database_test' -U postgres
