development:
  adapter: postgresql
  encoding: unicode
  database: todon
  pool: 5
  username: todon
  password: todon

test:
  adapter: postgresql
  encoding: unicode
  database: todon_test
  pool: 5
  username: todon
  password: todon

production:
  adapter: postgresql
  encoding: unicode
  database: todon
  pool: 5
  username: todon
  password:
